version: '3'
services: 
  web:
    build: ./web
    ports:
      - 3001:3000

  serverc:
    build: ./serverc
    ports:
      - 3002:3000
    
  nginx:
    image: nginx
    ports:
      - 8080:8080
    volumes:
     - ./web/public:/srv/www/static
     - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
    - web
    - serverc